name: release build
on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: 'develop'
        fetch-depth: '0'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "^1.17"

    - name: Get dependencies
      run: |
        go mod download -x

    - name: Build
      run: |
        bash scripts/make_release.sh gzip amd64 purego

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: cloud-torrent
        path: cloud-torrent_linux_amd64_static.gz 
